/**
 * @param {string} description - Adds an item to the database.
 * @param {string} [inputs] name - The name of the item
 * @param {string} [outputs] itemid - Returns the autogenerated ID of the item
 * */
app.post('/item', (req, res) => {
  res.send(item);
});
